### ISSUE TITLE
Change consolidated extension URL

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#172]
To http://standard.open-contracting.org/profiles/ppp/schema/1__0__0__beta/extension.json

Instead of http://standard.open-contracting.org/profiles/ppp/latest/en/extension.json

As discussed in #159

**Comment by duncandewhurst** [comment]
noting that #160 lists the places where this url needs to be changed

**Comment by jpmckinney** [comment]
Standard's instructions for copying schema into place are at http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/#copy-the-schema-into-place which we can then update for profiles at http://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/technical/deployment/#copy-the-schema-into-place

**Comment by duncandewhurst** [comment]
I've updated the URL where it occurs in this repo (https://github.com/open-contracting/public-private-partnerships/pull/178) and in the ocds_ppp_extension repo (https://github.com/open-contracting-extensions/ocds_ppp_extension/pull/5).

I don't have edit access the latter repo so I've forked it, made a PR and manually edited the url in the readme in this repo, so we don't need to run `apply-extensions.py`.

The build seems to be failing since I merged https://github.com/open-contracting/public-private-partnerships/pull/176 earlier but I'm not sure why as the branch I merged was passing.

**Comment by jpmckinney** [comment]
Aha, I've changed the default permissions for members of open-contracting-extensions to "Write".

I had made a change to the standard-maintenance-scripts to fail if `"schemas"` wasn't provided in extension.json. I've merged the PR that added that field, so tests should be passing in new builds.

**Comment by jpmckinney** [comment]
Closed by #178 and open-contracting-extensions/ocds_ppp_extension#5
