### ISSUE TITLE
milestoneCode codelist is missing from the documentation

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting-extensions/public-private-partnerships#188]
The [milestoneCode codelist](https://github.com/open-contracting/public-private-partnerships/blob/1.0-dev/schema/patched/codelists/milestoneCode.csv) is missing from the codelists page of the documentation.

The schema reference for `milestone/code` doesn't currently link to the milestoneCode codelist - this should be updated once the codelist appears in the PPP extension.

**Comment by jpmckinney** [comment]
As with #186, rather than change the `description` through an extension, we can perhaps add a sentence to the patched schema when it's built by `build-profile.py`. These issues suggest that perhaps URLs should be stored outside descriptions – to avoid having to manipulate normative content when changing URLs.

**Comment by jpmckinney** [comment]
Merged into #186 as the solution will be the same.
