### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by pindec** [open-contracting-extensions/public-private-partnerships#192]
Search in PPPs documentation appears to return no results regardless of search term.

E.g. [search for OCDS](http://standard.open-contracting.org/profiles/ppp/latest/en/search/?q=ocds&check_keywords=yes&area=default).

**Comment by jpmckinney** [comment]
@kindly I think https://github.com/OpenDataServices/standard-search isn't indexing any of the profiles. Can you add the `ppp`, `eu`, `gpa` profiles to the index?

cc @duncandewhurst

**Comment by jpmckinney** [comment]
In the short term, on the profiles, we *could* use a branch of the standard-theme that reverts the substitution of the new search backend, but if the fix is quick, then I'd rather pursue the fix.

**Comment by kindly** [comment]
Current status of this:

- I have manually indexed the `latest` `ppp` branch and the `master` `eu` branch, the above is now working.  I can easily index any branches people want as the standard search command line works for profiles.
- The `gpa` profile is causing issues with the index due to the big embedded table (actually due to a tr having class `section`).  This can be fixed pretty easily.
- The work of automatically indexing new pushed branches (as they do for the core standard) will require some work as the relevant travis.yml files need to be updated, secrets added to travis and the indexing API endpoint needs fixing as it currently assuming that all profiles have `en, fr, es` langs and fails on languages that are not there.

**Comment by duncandewhurst** [comment]
great, thanks @kindly 

The same issue is also affecting the search in the [infrastructure docs](http://standard.open-contracting.org/infrastructure/latest/en/), would it be possible to add that to the index?

**Comment by kindly** [comment]
@duncandewhurst I have indexed the `infrastructure` docs.
As this does not live under the `profiles` url then this might be another edge case to consider when doing the above work.

**Comment by duncandewhurst** [comment]
@kindly brilliant, thank you. I opened an issue in the infrastructure repo so we don't forget there is a manual step for now

**Comment by jpmckinney** [comment]
Search is working again. I opened a general search issue here: https://github.com/open-contracting/standard-development-handbook/issues/205
